---
- name: Adding Updating Legal Notice Title
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    name: legalnoticecaption
    data: "{{ title_legal_notice }}"

- name: Ading Updating Legal Notice Text
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    name: legalnoticetext
    data: "{{ text_legal_notice }}"



