---
- name: install the iis web service
  hosts: windows

  tasks:
    - name: Install multiple packages
      win_chocolatey:
        name: "{{ choco_packages }}"
        state: present

    - name: Chocolatey temporary patch
      win_shell: C:\ProgramData\chocolatey\bin\choco.exe feature disable --name="useEnhancedExitCodes"