---
- name: install chocolatey package on Windows host
  hosts: windows

  tasks:

    - name: Chocolatey temporary patch
      win_shell: C:\ProgramData\chocolatey\bin\choco.exe feature disable --name="useEnhancedExitCodes"

    - name: Install multiple packages
      win_chocolatey:
        name: "{{ choco_packages }}"
        state: present

