---
- name: install chocolatey package on Windows host
  hosts: windows

  tasks:

    - name: Use win_product_facts
      win_product_facts:

    - name: print out ansible vars
      debug:
        var: ansible_distribution
    
    - name: Chocolatey temporary patch
      win_shell: C:\ProgramData\chocolatey\bin\choco.exe feature disable --name="useEnhancedExitCodes"
      ignore_errors: true
      when: Server in ansible_distribution 

    - name: Chocolatey temporary patch
      win_shell: C:\ProgramData\chocoportable\bin\choco.exe feature disable --name="useEnhancedExitCodes"
      ignore_errors: true
      when: Windows 10 in ansible_distribution 

    - name: Install multiple packages
      win_chocolatey:
        name: "{{ choco_packages }}"
        state: "{{ app_state }}"

