---
- name: install the iis web service
  hosts: windows

  tasks:
    - name: install iis
      win_feature:
        name: Web-Server
        state: present

    - name: start iis service
      win_service:
        name: W3Svc
        state: started
    - name: Customize the homepage with Jinja2 Template
      win_template:
        src: ./templates/homepage.j2
        dest: C:\Inetpub\wwwroot\index.html     