---
- name: modifying chocolatey source
  hosts: windows

  vars:
    name: chocolatey
    state: enabled
    source: https://chocolatey-server/chocolatey
    username: testusername
    password: testpassword

  collections:
    - chocolatey.chocolatey  

  tasks:

    - name: modifying chocolatey source
      win_chocolatey_source:
        name: "{{ name }}"
        state: "{{ state }}"
        source: "{{ source }}"
        source_username: "{{ username }}"
        source_password: "{{ password }}"

