---
- name: install the iis web service
  hosts: windows

  vars:
    catagory1: Critical Updates
    catagory2: Security Updates

  tasks:

    - name: Install Windows updates
      win_updates:
        category_names:
          - "{{ catagory1 }}"
          - "{{ catagory2 }}"
        blacklist: "{{ blacklist_package }}"
        reboot: yes
        reboot_timeout: 1400


