---
- name: Create Windows Domain Group if it does not exists
  win_domain_group:
    name: "{{ win_group_name }}"
    scope: "{{ win_group_scope }}"
    state: present

- name: Create AD User
  win_domain_user:
    name: "{{ win_user_name }}"
    firstname: "{{ win_user_firstname }}"
    surname: "{{ win_user_surname }}"
    password: "{{ win_user_password }}"
    state: present
    email: "{{ win_user_email }}"

- name: Send Email with Report
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ gmail_account }}"
    password: "{{ gmail_account_password }}"
    to: "{{ sendto_email }}"
    subject: "New Employee Account Creation"
    body: 'Your new employee can login for this first time with the follow account info. They will be prompted to change thier password.\n username: "{{ win_user_name }}"\n "{{ win_user_password }}"'
  delegate_to: localhost
  